schema: ./graphql/schema/schema.graphql
documents: ./src/**/*.{graphql,js,ts,jsx,tsx}
extensions:
  codegen:
    generates:
      ./src/gql:
        preset: gql-tag-operations-preset
    hooks:
      afterOneFileWrite:
        - prettier --write
