module.exports = {
  content: ["./src/**/*.{html,js,tsx}"],
  theme: {
    colors: {
      black: "#121212",
      offblack: "#333333",
      blue: "#156FF7",
      "blue-light": "#B9D4FD",
      "blue-alt": "#346DEE",
      "blue-dark": "#102d70",
      "blue-darkest": "#002256",
      "blue-gray": "#F5F8FA",
      charcoal: "#242424",
      gray: "#CECECE",
      "gray-light": "#DBDBDB",
      "gray-lighter": "#F5F5F5",
      "gray-dark": "#2F2F2F",
      "gray-subtitle": "#B5B5B5",
      red: "#FF0000",
      white: "#FFFFFF",
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1364px",
    },
    extend: {},
  },
  plugins: [],
};
