import {
  getDashboardStore,
  getUserProfile,
  createEvaluation,
  deleteEvaluation,
  deleteSubmission,
  setEvaluationName,
  setEvaluationStatus,
  setSubmissionName,
  createSubmission,
  getVotingStore,
  getEvaluationStore,
  upsertVote,
  resetVotes,
} from "./methods";

export const MethodLookup = {
  getDashboardStore,
  getUserProfile,
  createEvaluation,
  deleteEvaluation,
  deleteSubmission,
  setEvaluationName,
  setEvaluationStatus,
  setSubmissionName,
  createSubmission,
  getVotingStore,
  getEvaluationStore,
  upsertVote,
  resetVotes,
};
