import {
  getDashboardStore,
  getUserProfile,
  createEvaluation,
  deleteEvaluation,
  deleteSubmission,
  setEvaluationName,
  setEvaluationStatus,
  setSubmissionName,
  createSubmission,
  getVotingStore,
  getAllEvaluations,
  getEvaluationStore,
  setVote,
  setResetVotes,
  setEvaluatorSubmission,
} from "./methods";

export const MethodLookup = {
  getDashboardStore,
  getUserProfile,
  createEvaluation,
  deleteEvaluation,
  deleteSubmission,
  setEvaluationName,
  setEvaluationStatus,
  setSubmissionName,
  createSubmission,
  getVotingStore,
  getAllEvaluations,
  getEvaluationStore,
  setVote,
  setResetVotes,
  setEvaluatorSubmission,
};
